version: '3.8'
services:
  cryptopia-node:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - PUBLIC_IP=0.0.0.0
    stdin_open: true
    tty: true