version: '3.8'
services:
  cryptopia-node:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      PUBLIC_IP: ${PUBLIC_IP}
      APPLICATION_INSIGHTS_CONNECTION_STRING: ${APPLICATION_INSIGHTS_CONNECTION_STRING}
    stdin_open: true
    tty: true
    env_file:
      - .env