version: '3.8'
services:
  cryptopia-node:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file:
      - .env
    environment:
      - PUBLIC_IP
      - APPLICATION_INSIGHTS_CONNECTION_STRING
    stdin_open: true
    tty: true
