version: '3.8'
services:
  cryptopia-node:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - PUBLIC_IP=${SERVER_IP}
      - APPLICATION_INSIGHTS_CONNECTION_STRING="Test"
    stdin_open: true
    tty: true