name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Deploy to Droplet
      env:
        SERVER_IP: ${{ secrets.DIGITALOCEAN_SERVER_IP }}
        APPLICATION_INSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATION_INSIGHTS_CONNECTION_STRING }}
      run: |
        ssh -o StrictHostKeyChecking=no root@$SERVER_IP << 'EOF'
          cd /root/cryptopia-node
          git fetch origin
          git checkout master
          git rebase origin/master
          git pull origin master
          docker-compose up -d --build
        EOF
